### ISSUE TITLE
Handle expired keys

### ISSUE THREAD

**Issue by 4x0v7** [4x0v7/ghaction-verify-gitobj#12]

**Comment by 4x0v7** [comment]
```yaml
  test:0:tag:annotated:
    cmds:
      - task: dev
        vars:
          INPUT_REPO: https://github.com/LeSuisse/vault-gpg-plugin
          INPUT_TAG: v0.5.0
          INPUT_PUBKEY: 204FE7416FCFA155
```
